version: "3.7"
services:
  vmq0:
    image: vernemq/vernemq
    environment:
      # DOCKER_VERNEMQ_SWARM: 1
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
    ports:
      - "8888:8888"
  vmq:
    image: vernemq/vernemq
    depends_on:
      - vmq0
    environment:
      # DOCKER_VERNEMQ_SWARM: 1
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
      DOCKER_VERNEMQ_DISCOVERY_NODE: vmq0
    ports:
      - "8888"
    # deploy:
    #   replicas: 3